# LIST [ ] (square brackets)

In [ ]:
#List iteration
student=["M","A","V","I"]
for i in student:
  print(i)        #each output printed differently
#printing list
print(student)    #output in array format

M
A
V
I
['M', 'A', 'V', 'I']

In [ ]:
#length of list
l = len(student)
print("Length of student is: ", l)

Length of student is:  4

In [ ]:
#add new element to the end : append()
#add elements to specific position in list : insert()
#list_name.append("value")
student.append("R")
print(student)

#list_name.insert(index,"value")
student.insert(1,"S")
print(student)

['M', 'A', 'V', 'I', 'R', 'R']
['M', 'S', 'A', 'V', 'I', 'R', 'R']

In [ ]:
#remove element
#list_name.remove("value") #need to add the value/instance that should be removed, not the index
student.remove("R")
print(student)

['M', 'S', 'A', 'V', 'I', 'R']

In [ ]:
#program to interchange first and last elements in a list
list = ["Anna", "Shein", "Kali", "Stella"]
print("The original list is:",list)

#logic to reverse first element(from start index 0) and last element (first element from end)
list[0], list[-1] = list[-1], list[0]
print("The list after interchanging first and last elements:", list)

In [ ]:
#cloning or copying a list into another list
things = ["Hat", "Bat", "Cat", "Mat"]
print("The original list 'things' contains the elements:", things)

#logic to copy elements of one list to another
also_things = things
print("The cloned list 'also_things' contains the same elements:",also_things)

print("\nCloning successful!")

# TUPLE ( ) round bracket

immutable elements, cannot be changed

add(), append() functions will give error

In [ ]:
#creating tuple
#tuple_name = ("val1","val2",...)

fruits = ("Apple", "Banana", "Papaya", "Mango")
print(fruits)

print(fruits[1])      #print a specific element at index
print(fruits[0:4])    #print from:to (range)
print(fruits[-2])     #index starts from end

for i in fruits:
  print(i)

('Apple', 'Banana', 'Papaya', 'Mango')
Banana
('Apple', 'Banana', 'Papaya', 'Mango')
Papaya
Apple
Banana
Papaya
Mango

In [ ]:
#program to create a tuple of numbers and print it in reverse.
num = (1,2,3,4,5,6)
print("The original tuple is: ", num)         #normal output
print("The reversed tuple is: ", num[::-1])   #reverse output (start index: end index: step (-1 denotes step in reverse))

# SET { }

- does not contain duplicate values
- output is not sequential

In [ ]:
days = {"mon", "tue", "fri", "sat", "sun"}
print(days)
for i in days:
  print(i)

{'sun', 'tue', 'sat', 'fri', 'mon'}
sun
tue
sat
fri
mon

In [ ]:
#cannot contain duplicate values
days.add("fri")
print(days)     #there will not be two fri values

{'tue', 'sat', 'sun', 'fri', 'mon'}

In [ ]:
#copy set from one to another
set = days  #copy one set to another
print(set)
#set = {}    #create empty set also possible

{'sat', 'fri', 'mon', 'tue'}

# DICT {}

In [4]:
dict = {1: "Random", "Blair": "Counter"}
print(dict)
dict["nano"] = "Five"
print(dict)

print(dict[1])

{1: 'Random', 'Blair': 'Counter'}
{1: 'Random', 'Blair': 'Counter', 'nano': 'Five'}
Random